"""Pydantic v2 data models for LastroSEO POC."""

from pydantic import BaseModel, Field


class CompetitorData(BaseModel):
    """Parsed data from one SERP competitor URL."""

    url: str
    title: str = ""
    meta_desc: str = ""
    h1: str = ""
    h2_h3_map: dict[str, list[str]] = Field(
        default_factory=dict, description="{h2_heading: [h3_subheadings]}"
    )
    word_count: int = 0
    media_count: dict[str, int] = Field(
        default_factory=lambda: {"img": 0, "video": 0}
    )
    text_content: str = ""


class Briefing(BaseModel):
    """Final SEO briefing — output of analyzer, input to writer."""

    keyword: str
    search_intent: str
    paas: list[str] = Field(default_factory=list)
    semantic_kws: list[str] = Field(default_factory=list)
    content_gaps: list[str] = Field(default_factory=list)
    target_word_count: int = 0
    proposed_structure: list[str] = Field(
        default_factory=list, description="Ordered list of H2 headings"
    )


class BrandGuide(BaseModel):
    """Brand voice, tone, and editorial rules loaded from YAML."""

    tone: str
    persona: str
    rules: list[str] = Field(default_factory=list)


class StoryArc(BaseModel):
    """Storytelling plan — generated by LLM after briefing, before writing.

    Guides the article writer to produce a compelling narrative instead of
    a dry keyword-stuffed list.
    """

    angle: str = Field(
        default="",
        description="Narrative hook or unique angle that makes the article stand out",
    )
    target_audience: str = Field(
        default="",
        description="Who this article is written for (e.g. 'gestores de CX em médias empresas')",
    )
    arguments: list[str] = Field(
        default_factory=list,
        description="3-5 key arguments the article must defend, in logical order",
    )
    emotional_arc: str = Field(
        default="",
        description="Emotional journey: problem → tension → resolution → call-to-action",
    )
    section_plan: list[dict[str, str]] = Field(
        default_factory=list,
        description="Ordered sections: each has 'h2' (heading), 'goal' (what this section achieves), 'tone' (emotional register)",
    )


class ProductInfo(BaseModel):
    """Product/service context — loaded from a .md file via --product-doc.

    Never mentioned directly in the article except the final CTA paragraph.
    The storyteller uses this to align arguments with the product's value prop.
    """

    name: str = Field(default="", description="Product or service name")
    description: str = Field(default="", description="One-line elevator pitch")
    value_prop: str = Field(default="", description="Core value proposition")
    cta: str = Field(default="", description="Call-to-action text for the final paragraph")
    raw_markdown: str = Field(default="", description="Full product document content")
